<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Staging Smoke Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-06-05T12:07:43</lastRun>
   <mailRecipient>ksavinkin@tula.co;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a864f51a-8c1f-4260-9dac-2e4cd7df1d5a</testSuiteGuid>
   <testCaseLink>
      <guid>f4f4c556-cf4f-417a-9cc6-bfef53cc888e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckHomeSliders</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>84d42677-e4e1-4fb0-8904-0cd5514bb746</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHome - EmptyVIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d344089-46a0-4e72-b8fb-413740430d19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9840b010-f208-4a38-9a58-b044010f5310</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHome - NoSticker</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49a2045b-14db-4a23-b416-235cc6cbc597</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7f56409-2ede-45b2-b4c0-4b2615d9ed16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHome - ShortVINwith9Digits</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>485aea01-053e-4b49-8d8d-dc947cfdc35e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1118a064-8618-4988-9c53-8ce66b2133b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHome - Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22c410be-f0bd-4c38-990d-76f47a5e1137</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c959497d-d60f-45dd-81a2-2733d4c9a8fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpConsumer - EmptyFields</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cf7886b7-a4eb-4cbf-83e4-3fc28b77506b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpConsumer - IncorrectEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7d1591a-1071-4b5d-b65a-96c19821c944</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88f9b00d-7f84-4304-bfd3-54908075a787</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpConsumer - ShortAndMissmatchedPass</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c83424-84e0-471e-83e5-7a26a243bf88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46c69eb1-2baf-4c2f-b033-f82d18b4efac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpConsumer - CopyBuyer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dbeea45b-b5b2-48cf-8db5-4131e9347908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - EmptyFields</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3e34fd-fb39-42a0-895b-0e61de2cac44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - HiddenField</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>301fbea0-939d-4660-b29f-320e4250c884</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7cef621-e6f8-4067-b4fa-dede1f5ad56b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - IncorrectEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86e94bf0-528c-468f-8d98-7a7c5e8899bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>908b3fa9-7b85-458c-a6cb-2ad6a6eecdc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - ShortAndMissmatchedPass</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89017502-a143-4fb4-8ae3-22cb168bcb9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6633c330-d922-4f24-a25e-af381c20f88a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - CopyBuyer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4cfb6673-908d-4a2c-804d-a1880382e36e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpConsumer - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d98ce8-10ee-4e1d-9744-bcb7f04fa7b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a759bb66-289c-4665-adc0-b8afc4589c00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d502b2c-a897-4104-8a5b-a02433637e5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88d54719-7c33-4134-a76b-0b46d5136936</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48577bf-bb36-4f16-b5bd-ab8883f6bc10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56e740e2-b0a4-4876-b243-dd9825749724</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2684375e-abbe-41ab-82d8-1ae847db54f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpDealer - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e90b5721-ab5e-473e-b479-4b95bb0efc73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69bcb8a6-2d87-4724-adbf-0fb06bce6a80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1814d653-1443-4535-97bb-f3faa34063a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18e7c03d-1142-4ead-93ac-32a13a4211c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cfdbb84-eaf8-4e27-aa5f-dc61b27acb67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ff2471-2cd9-4a76-b7d2-3d315d7ba50c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aa55b57-f0bc-40f1-a009-dfc59a871604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>060fa72a-baff-40cb-bbd6-d39501825215</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97ef3c01-afa9-4a37-ba4a-55e6a2ad4c8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUpCADealer - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c096d10e-7c35-4a34-b3a9-189d8361b956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6035890c-3ed8-4b2d-b36e-ab3822453ed8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f40616-adae-4010-a16c-2399fe00dbd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a744400a-8c81-4ba0-9d2e-da20b9192f63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d98034f0-526c-4b95-a21c-71c4e51b5abb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41f7b486-badd-4374-bfb7-da16543f1ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>241afada-8401-4626-9d2d-ae61c18f3999</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>310cae22-a7b7-49ac-b03c-6fb4c8cc6784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9642f6c-ae5d-47c6-ab60-b890337da460</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginEmptyEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b20fe411-e366-44c8-a54f-000b1118baf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71639f3e-8158-45d9-8b42-a079dc0adb52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginWrongPass</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2435ff-edf7-40ad-9c08-5d8330695407</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e960120f-93e2-4ed6-9cf0-fd3194f49d30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49082ecb-a6f1-424f-ab01-bf2a3f432d57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fd38075-a323-4dc9-a523-72bdfd27a0fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginSuccess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd6dd04-e6cd-419d-b812-5e386bbddfd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cc88f30-ec50-4bce-a3e2-fea29f8d1b65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11ac2a74-cbda-4c65-9098-986532790313</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd63a0e5-f524-443c-a327-48f3499397b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BillingInfo - CheckCurrentCard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a72a0cab-5965-4077-8064-e0450854d9e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef6bd37f-691e-41c5-bf67-263ca4fee133</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4a824f-3fa0-40f5-b07f-d8fa7613e20f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e048079-1fe7-43e3-abde-8175df7b2eb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a255048-c06d-4eab-97d7-725c50e5ce77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d80d64e0-b6ca-4112-9207-9c4ade47c295</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHomeLoggedIn - EmptyVIN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef7434d6-791b-442f-b52c-4c37e39ff222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1076a21a-76f9-4465-82ec-4dcebf0432d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c027c201-f446-4e82-8c2d-1af3a0040127</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>caa6ac5d-341c-47ed-85dc-b5a5cd7155be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHomeLoggedIn - NoSticker</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7aceda5-fcf4-4dd0-9f58-31061a813b77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8096c2c9-f047-47f2-a06d-d4cbe2e43293</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>717fd91a-11d0-4831-ae41-5e232225054c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42715268-7efd-43cf-bb01-9385602084f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHomeLoggedIn - ShortVINwith9Digits</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3172bb8f-2730-4ef1-a295-f6797e7f6e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b19423d-cbc5-4fa0-97db-73286b48bdcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce032d59-e93c-430c-a1f9-74f69c5c2bc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98222838-7a9f-477f-9706-9c5bd05cef4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckVINfromHomeLoggedIn - Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcec3bc1-3d86-44a8-8eeb-2a64f99279f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bc5d704-076d-48c3-b6bc-420b8d6ababb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e68f59f2-c353-44a8-8a1c-b773751c13e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b867ab7-65b3-405b-acae-5ee041a251e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CaDealerRequest - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cbe597e-24db-4c2c-88d5-77103d9d9db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1fbe2e5-cb22-4866-9c1b-e8d01991c8cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ec9fd08-03f1-474b-98e3-ca7cfc54eedb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65230304-557a-45a9-8dc8-056bce45988b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DealerRequest - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d0e1e2-8a72-4776-80d0-4309b1595979</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de69ee8a-68ae-42c6-a038-9b4ca9081ac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5d53311-c794-4528-99e6-b622737a1e5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c67ccde-62d1-4e46-8f13-94af4192869f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Affiliate - BuyVTRConsumer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f28261c0-9c29-4f16-9218-ae84650c838a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8f1f31d-6baa-48c2-be07-d8eb8411b513</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>758407c1-2c69-4431-a72c-2aa474157aa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1467fdaf-f2f8-4cb0-953a-6d27ee12b66b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6216b55-55fa-4efa-bddb-521c5dbb65d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60b2af48-cbf0-4f2a-ba09-53fe55b664f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e3a2e3a-31ae-4e3d-bd66-bfae6b9ef7ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06decd4d-3361-4c98-909a-200b854fbc45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2edc7e-3ed2-4415-aa33-b76e9c7e382d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d156dcb-1d54-43ee-9645-d8b7e8994569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf2f71c3-68e0-4470-bdeb-2fd969bc1c2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07f23280-b590-4d3d-b4eb-44bdd3515f0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Affiliate - BuyVTRDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcb92bc-faef-48ac-ba70-269a1ed7300f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edfd65da-8130-4393-a11e-2b3fbad8946a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18d73a51-0d10-4082-8f24-408e4d8d7df5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>469446aa-8f46-43fa-bf1d-a9ba92a88ed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61cbe5d1-ad79-46b6-a9a3-be9ddb986c1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3e13a0-f28f-4a11-8f0b-f527989a63fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2469693d-4bcc-4fea-a5fe-4292fcca8872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d81c2825-a7ce-4ead-aa67-4f91a6faee7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ab99c5-a20b-4d18-9d7b-9dd54a62540a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc2936d-b76f-4f56-9b23-667bb7065a62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6120db24-2996-4d2c-bd9b-284215544602</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8a9966-3b0f-4ddc-885c-134ae3c1881a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7de05f59-8c5c-4c28-991e-6e256a92e39f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Affiliate - BuyVTRCaDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bb3a958-a34c-4ae5-a502-38d80e563817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9e02d3f-27a0-44b1-9ba4-98afacfce2cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81d8bc5d-9e47-4c63-ad36-9dd67a5337db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9117aff5-8a16-4a7f-a241-1ce13a5b2f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a9bd2a3-0cae-4d8a-bf94-996a48aacc0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f3dd9e6-2317-4cde-9caa-9de732eb0c64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189d5a88-080c-4d8f-b253-564cfffe6fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>054a1c04-2907-4cc5-90bd-ab43ed6447ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d2a19bd-7810-4759-94fb-8eeebdf4efb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51317586-edaf-4c51-bc40-9b64d6592efa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145a9742-b4ec-4b48-85c8-abb2e964381f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb68c637-9df9-454b-91bc-1ac2a044c43b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f75bad8-1ad8-4ff8-89eb-56b1d0e28acd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Salesman - BuyVtrCaDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c2088ab-1b07-4436-92c6-9d7bca0457d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c6670e5-0aae-4f97-9bf3-86648bee2e03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c9b454-2dff-48b7-a3c4-6f2f913655f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f76fde00-8c1f-49ab-ba4f-d41d22a8fb33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08d2a9d6-4769-4e1f-9ab0-2422eefbe479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee880e3-bad4-49f2-867b-f6741360ff6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c1f8de-30ca-4424-9281-0a803b00b180</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a331a949-4195-45e0-bcd3-7af9a7358cad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f9cf12e-f87e-41e4-aa74-bd23e637b31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce77e96e-34c9-4a1d-917a-712a6edffc8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143cd352-cee6-414b-87ae-21263d59243e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24e28a89-b80d-42ae-a6a9-efd18d261652</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Salesman - BuyVTRConsumer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8adafe37-40a8-42fb-af55-6eacd9b12a11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6191cb-008a-4dc3-b79f-8393b9b57820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcb08b4c-5f07-474b-a503-50063c7910bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dc10c7b-fe90-4fde-af44-f10f7409a529</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a6135b0-4a52-4f82-a1d1-3054311187a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a877fa8f-78b6-4d5d-a3a8-df92dff95166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>331e8e05-ecc4-4771-8c2e-812406470506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5c106ff-c118-46a3-86d3-142a2a0f6624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2421d124-c051-47f7-9131-38a39fd54aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9f48cdd-7d59-4ce0-ace0-5c23959fc3d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d1a44a-0b07-4181-9441-902b88f711d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72118754-274f-4853-b8cb-7b2cc657c22d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Salesman - BuyVTRDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f5a1190-5d40-4114-a595-c281448ec0a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d569bbc-6890-4006-ac92-37a8ec6e0dc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cd46c47-1ec5-43ae-991c-226443f15220</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>148e5b57-238d-409f-a630-45663eeb1775</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2bc1d45-f365-46b5-915a-e8152ced66fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26570329-efc8-4293-8a3f-a28022f3b44c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f98a3f1-c2eb-494e-948f-368b8a7094ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95bd2a40-524b-42d0-8325-aae4f86d86c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>408c20d0-da09-475f-b54e-68ff5443a56a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a49d7f90-f153-4e03-aef4-c07eb08d9d0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cd0cbd-5cad-43f4-8acf-9efa2ef094b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd1b88b6-3865-4540-a1e8-d4c18ca2ed50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AffiliateRequest - ValidFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad4cac80-3431-41ff-a607-3478964f4974</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817cf0f0-26dd-4f15-8816-2e7edc2ff4a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e50f97a-e24e-4579-bb96-5f70fbbdc844</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa21faee-71fa-4e37-8a21-1bef38a48272</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - BuyVtr_CautionRecall</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d66b9e96-5053-4e46-b1a3-c33c82ec9b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb98400a-c610-4abc-af75-def886063f63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a68c72cc-cc3c-4808-a40c-c6dc24378bc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e34f31ad-5513-45e9-805e-4cdfdca14355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>702a1dc7-bcd0-4a99-a15a-0f8d56ceb214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b606846f-35fd-42f9-8f4a-0b0341df6f79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c637dc7-363f-40b8-aaa4-8cb2f39c6933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16f729ec-b6bb-47ea-96cf-de3751c5bebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95fcbef2-0676-4dc0-b974-5378e60d1159</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65b39831-542b-454a-a406-b4b3249637bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd01bdb4-0417-4d9f-a70c-1364d569f6f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - BuyVtr_NoProblems</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93847935-d8b4-4f23-a6cd-90f715d74242</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>678e8a9b-b475-411d-a4b9-582b4ebc485e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e947da9-fc2f-4f29-aa20-fe9c6ab4897d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83ae65aa-2e42-406f-9383-4079d21875e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85299ce7-f7f1-47cf-bb7f-c59ffe3f0a55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e60b520-229b-43a5-a6ba-0fe9a144ecda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66cb907b-aabb-4b64-ac4e-cc9096426e75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6d9088-a5d9-4e8b-9ade-f7924a2db1f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08cac9ba-fc49-403d-84e6-2c0315fa0804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd0bc66a-7995-4593-aafc-3f7d68805fc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>280474fa-d0aa-4946-aa8a-b924639dcc30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - BuyVtr_CautionTitle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d29c18ed-1df3-4761-be0f-28c36be287f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10b3d13d-e01c-41d2-906b-2fc92c993ca8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68bd9857-8933-4b7f-bda8-64a069da3c8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19474c20-c24c-466d-8cf1-99fe5621e218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f25ea794-c0b0-4396-bd5f-fb315441fea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8e2f3de-c5ab-4ac4-97cd-0c60c35a7070</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1547002-2340-490e-92fb-33d5a5a837f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84bea3ba-7342-4f5c-85bf-b5d157f8186e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d236b68e-a07c-4df7-9e06-4efd6f2ba3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93bd4823-58f7-4f8c-8c2c-3331aeffdead</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9712e060-e1c9-4938-a7e4-540f75b6da7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - BuyVtr_UseCredit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5372a469-9c42-49db-abae-a46bcbdf04d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>880ae5f2-2409-4cad-932a-40f67cbb7777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58119efe-e866-4675-84e8-ec5c0ee4cc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>998ecf97-f60b-4cb5-a556-1e390257cdff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5151617-4a68-43b6-b6a6-ef2fd7282fae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba1113f-6fbe-4522-a1cb-745c2557eeab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a45ca0-19e8-4895-a89e-cd3abb14da56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb02b53e-dac1-4c20-a7d5-3ee51e3d1f25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e1254ec-f497-4998-a43c-03e635d2203e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3811570f-4265-4777-93fa-5c42b6106e81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>780cd161-f29a-40e8-8a13-c0fd40b02584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b240d903-732b-4b79-85f1-0ec4a454def0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>773fa5fb-1050-41fc-b1c5-dae67fff3e8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - BuyVtr_WarningSalvageTitleRecall</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff86e250-88d3-4cfe-a7dd-dfa753d4ac26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2939973-9746-4202-80ce-f7817822ff5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8876d0e-b662-4a98-9d7a-53375a23da61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>894a8d99-33ba-45c4-92e9-aeae20116402</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282c9801-e4f5-49df-921e-a2be25eb2600</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f42354-b78f-40b9-8afe-fdc98764035c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2336f887-e271-46cc-b551-0d9718f577f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a494e3e-3e45-447b-9b91-48b1de839bea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49bb767d-737b-4086-8bb1-f7535953fe09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a85e8379-4cf3-41fe-b986-90d623e89b16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52d32f79-81f3-441b-89f2-a50bb3df0fcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - ByVtrGrantCredits</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b840ddb-7a1c-4a18-9024-bfb36ab382aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa9835c9-2f6c-4f9c-b161-5a483a9a1555</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>029c0b45-1f7e-48fa-be1c-4295a1a1f939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93172456-1393-4cc9-ae28-10a827a13c3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>868e4593-2196-4096-99e1-8a52b2d201c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Order - ByVtrNoGrantCredits</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08977d9e-f529-44e4-8487-156bfa418c05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c6c69c5-e40d-4239-86ff-7701b2d5b0a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d821d30c-8cb6-4bc0-8b65-6296a5bd97f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>285bed62-5854-4d90-8bd8-128ed0f2f01a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7e59672-2075-403e-bbd5-7b1a48a8f96c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ApiDocs</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>94e00e16-c156-41ca-8bed-9041abca6f51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginPage - WrongPass</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827763d6-a840-4a3d-b479-df20d7b5439d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>655bfae2-2258-4ad2-95a4-20636c091d5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a1d3819-10d9-469d-8446-613fffe26cd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6294e5f-348f-4bba-bee3-bad749dd271f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginPage - EmptyEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>581443db-b69f-41d0-a97c-8a91bcf56f35</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
