<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingFirstName_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>d3297fb4-0975-4457-8952-1ae646a27271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='BillingInfo']/div[2]/div[1]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
