<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusinessLastName_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>9d84c276-8dd5-4bf1-9a8a-e20bd4d897ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='BuyerInfo']/div[2]/div[2]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
