<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusinessPhone_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>48e5a978-8d30-4283-a3dc-6854b0ed4cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='BuyerInfo']/div[4]/div[1]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
