<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusinessCity_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>0e40f7b9-1f07-490d-a046-c19a032d789b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='BuyerInfo']/div[3]/div[2]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
