<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CVV_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>70a2c061-0d87-4416-9f91-49dd33c5156f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[5]/div[2]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
