<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Input</name>
   <tag></tag>
   <elementGuidId>a6d74b1f-7316-40e8-adc8-2e2d44bad383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='AccountInfo']/div[1]/div[1]/div[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
