<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpirationMonth_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>00c4142b-36ef-4f01-aa99-83debc1c1fd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[5]/div[1]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
