<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastName_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>fa1434c7-629c-449a-9d99-6e59dbbcb240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[1]/div[2]/div[2]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
