<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password_Input</name>
   <tag></tag>
   <elementGuidId>7bc72bb7-fc75-4896-9038-01a444845778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@id='AccountInfo']/div[2]/div[1]/div[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
