<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VisaImage</name>
   <tag></tag>
   <elementGuidId>8ea4078d-d812-4a89-832c-cefc47914797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='https://ss.instavin.com/site/images/my-account/icon_visa.png']</value>
   </webElementProperties>
</WebElementEntity>
