<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AffiliateSignUp_Header</name>
   <tag></tag>
   <elementGuidId>8f5475a8-cfdf-49a8-bc63-1e5f11500a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1[@class='AffiliateSignUpFormTitle']</value>
   </webElementProperties>
</WebElementEntity>
