<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FactoryOptions_Link</name>
   <tag></tag>
   <elementGuidId>71ad44c1-99c1-43cb-8916-e9900ff2b44b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-index='1']//div//div[@class='SubSlideContainer']//div[@class='container']//div[@class='AppsSlide']//h1//a[@href='https://dev-front.instavin.com/build-data']</value>
   </webElementProperties>
</WebElementEntity>
