<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VehicleSpecsStatus</name>
   <tag></tag>
   <elementGuidId>f096006f-ffee-4f04-b3d3-23e192337bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='SummaryTileContainer']/div[@data-site-tab='{&quot;tabId&quot;:&quot;vehicleSpecs&quot;,&quot;selectedCss&quot;:&quot;&quot;,&quot;deselectedCss&quot;:&quot;&quot;}']/div[2]</value>
   </webElementProperties>
</WebElementEntity>
