<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstRowSecondSection</name>
   <tag></tag>
   <elementGuidId>df2ec768-080a-4098-867f-41c553705d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='swagger-ui']//div[3]/section[1]/div/div[2]/div/div[1]/div/span[2]/a/span</value>
   </webElementProperties>
</WebElementEntity>
