<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecondRowFirstSection</name>
   <tag></tag>
   <elementGuidId>98f2b934-36b2-4455-85d6-652cd48726b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='swagger-ui']//div[3]/section[1]/div/div[1]/div/div[2]/div/span[2]/a/span</value>
   </webElementProperties>
</WebElementEntity>
