<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecondSection</name>
   <tag></tag>
   <elementGuidId>21a0f128-943f-464a-bdf2-1b2ead2d001a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='swagger-ui']//div[3]/section[1]/div/div[2]/h4/a/span</value>
   </webElementProperties>
</WebElementEntity>
