<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThirdSection</name>
   <tag></tag>
   <elementGuidId>35446fa3-7a29-43fb-a7fe-1b9a17db4e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='swagger-ui']//div[3]/section[1]/div/div[3]/h4/a/span</value>
   </webElementProperties>
</WebElementEntity>
