<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstPricePoint</name>
   <tag></tag>
   <elementGuidId>5d96d962-8e8a-4182-94a9-efd99295b4d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='PricingPanel']/div[@class='PricingOptionsContainer']/form/div[3]</value>
   </webElementProperties>
</WebElementEntity>
