<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyAccount_Label</name>
   <tag></tag>
   <elementGuidId>f3547b84-a803-47fb-aff9-348fc079379c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//html//li[@class='HasDropdown']/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//li[@class='HasDropdown']/a[1]</value>
   </webElementProperties>
</WebElementEntity>
