<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VtrPrice1</name>
   <tag></tag>
   <elementGuidId>ff2c723a-3a87-491a-a62f-5b50c73292e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[@class='PricingOptionsContainer']/form/div[3]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
