<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SidebarLogo</name>
   <tag></tag>
   <elementGuidId>ef416f19-6192-408a-96db-76a604aecf49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class='SidebarLogoContainer']//a[@href='https://dev-front.instavin.com']//img[@src='https://ss.instavin.com/site/images/instavin-logo.gif']</value>
   </webElementProperties>
</WebElementEntity>
